projectName: '<cybersecurity_conference> Recap: Key SEO Insights for <cybersecurity_role>'
jsonFilePath: ./input.json
baseUrl: sun.com
portalHeading: 'GrackerAI: Cybersecurity Solutions'
portalDescription: >-
  World's first AI-driven growth engine for cybersecurity B2B SaaS. Engage
  prospects, demonstrate expertise, and fuel expansion through customized,
  data-backed content strategies.
portalTitle: 'Boost Brand Authority & Leads: GrackerAI for Cybersecurity SaaS'
searchPlaceholder: Search for cybersecurity insights...
useAlphabetsCategory: true
homeLink: sun.com
logoLink: /
ctaText: Get started â€” it's free
aboutLink: https://sun.com/about/
productsLink: https://sun.com/products/
logoImgUrl: https://sun.com/_astro/logo-white.DuNP12gY_Z22gpAz.svg
ctaLink: https://portal.gracker.ai/
copyrightText: '&copy; Copyright 2024, Gracker.'
faviconUrl: https://sun.com/favicon.ico
googleTagManagerId: GTM-MB8NQN6
pagesTitle:
  prefix: ''
  suffix: ''
categoryPagesTitle:
  prefix: ''
  suffix: ''
templateRoot:
  - ./templates
  - ./templates
homeTemplatePath: ./templates/homePageTemplate.ejs
categoryTemplatePath: ./templates/categoryTemplate.ejs
pageTemplatePath: ./templates/pagesTemplate.ejs
outputDir: ./output
socialLinks:
  - platform: LinkedIn
    url: https://www.linkedin.com/company/gracker-ai/
  - platform: Twitter
    url: https://x.com/grackerAI
  - platform: Instagram
    url: https://www.instagram.com/grackerai/
theme:
  primaryColor: '#ffffff'
  secondaryColor: '#000000'
  backgroundColor: '#f0f0f0'
  textColor: '#333333'
  accentColor: '#ff0000'
fonts:
  - family: Bricolage Grotesque
    weights:
      - 400
      - 500
      - 600
  - family: Poppins
    weights:
      - 400
      - 500
      - 600
